name: moderato-testnet
eid: MODERATO_V2_TESTNET
token_messaging: true
credit_messaging: true
tokens:
  usdc:
    type: oft
  eurc:
    type: oft
treasurer:
  tokens:
    usdc: true
    eurc: true
isTIP20: true
