name: tempodev1-testnet
eid: TEMPODEV1_V2_TESTNET
token_messaging: true
credit_messaging: true
tokens:
  eth:
    type: oft
  usdc:
    type: oft
treasurer:
  tokens:
    eth: true
    usdc: true
usdcTip20: true
