name: Offchain Checker

on:
  workflow_dispatch:

jobs:
  validate:
    name: Run stg-evm-sdk-v2 validation
    runs-on: ubuntu-latest-4xlarge
    env:
      NPM_TOKEN: ""
      RPC_URL_MAINNET: ${{ secrets.RPC_URL_MAINNET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Build
        uses: ./.github/workflows/actions/build

      - name: Run offchain validation
        working-directory: packages/stg-evm-sdk-v2
        run: pnpm run validate
